### ISSUE TITLE
무한스크롤 최적화 및 수정 기능 간헐적 미적용 문제

### ISSUE THREAD

**Issue by ddooyn** [ddooyn/my-dictionary-app-2022#1]
- [현업에서 무한스크롤 구현 시 어떤 식(디바운싱/쓰로틀링/...)으로 구현해서 최적화하는지 궁금합니다.](https://github.com/ddooyn/my-dictionary-app-2022/commit/11e9abae710d645c6cfa220837a3d53296accbcd)

- [단어 수정 시 리덕스 state 변화가 한번씩 동작하지 않아 리렌더링이 되었다가 안되었다가 하는 현상이 있는데 원인을 모르겠습니다. (파이어스토어 데이터 수정은 동작하고 있음)](https://github.com/ddooyn/my-dictionary-app-2022/commit/a4c7071902f8737a4902e24f523f4561d7085655)

**Comment by ddooyn** [comment]
- 모바일 환경 한정으로 무한스크롤 시 데이터를 중복으로 받아오는 문제도 있습니다.

> 궁금한 점이 많은데 이 중에서 코드 리뷰 하나만 해주셔도 감사드리겠습니다 ☺

**Comment by leedaeho1188** [comment]
제가 생각하는 무한 스크롤을 구현하는 방식은 크게 2가지가 있는 것 같습니다.

첫번째는,

> window.innerHeight를 이용해서 debounce, throttle & useCallback으로 무한스크롤을 최적화 시켜서 구현하는 방법이있습니다.
자세한 내용은 아래 링크로 들어가셔서 확인하실 수 있습니다.
[노션 자료](https://www.notion.so/4-b1e7190f00c948fca776e76227d0b559)

두번째는 

> Intersectionobserver를 사용해서 무한스크롤을 구현할 수있습니다. 자세한 내용은 직접 검색을 해보시면 많은 자료를 참고하실 수 있을 것 같습니다.


둘다 공부해보시면 많은 도움이 되실 것 같습니다.

**Comment by ddooyn** [comment]
@leedaeho1188 큰 도움이 되었습니다 정말 감사드립니다👍 공부해서 다시 구현해보도록 하겠습니다 :)
